-- Jeżeli identyfikatory w public.facilities nie są typu UUID, dostosuj typ kolumny facility_id.

create table if not exists public.facility_checklist_items (
  id bigint generated by default as identity primary key,
  facility_id uuid not null references public.facilities (id) on delete cascade,
  phase text not null check (phase in ('handover', 'return')),
  title text not null,
  description text,
  is_required boolean not null default true,
  order_index integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists facility_checklist_items_facility_phase_idx
  on public.facility_checklist_items (facility_id, phase, order_index, id);

create or replace function public.set_facility_checklist_items_updated_at()
returns trigger as
$$
begin
  new.updated_at = now();
  return new;
end;
$$
language plpgsql;

create trigger facility_checklist_items_set_updated_at
before update on public.facility_checklist_items
for each row execute function public.set_facility_checklist_items_updated_at();
